[snowflake]
SNOWFLAKE_ACCOUNT = "jdywsqb-xq29308"
SNOWFLAKE_USER = ""
SNOWFLAKE_PASSWORD = ""
SNOWFLAKE_DATABASE = "BANKING_ANALYTICS_BUNDLE"
SNOWFLAKE_SCHEMA = "BANKING_INSIGHTS"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"

OPENAI_API_KEY = "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"

[streamlit]
SUPABASE_URL = "https://whemmzbdmeaeajawzygu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZW1temJkbWVhZWFqYXd6eWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTgwMzM5MzQsImV4cCI6MjAxMzYwOTkzNH0.9BHaIJyz0cuaW8i3WlRJmWLo-TcDVfFhIXPVj7sOFGM"

