OPENAI_API_KEY = "sk-....."

[snowflake]
SNOWFLAKE_ACCOUNT = "hplxkon-ko97857"
SNOWFLAKE_USER = ""
SNOWFLAKE_PASSWORD = ""
SNOWFLAKE_DATABASE = "BANKING_ANALYTICS_BUNDLE"
SNOWFLAKE_SCHEMA = "BANKING_INSIGHTS"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"

[supabase]
SUPABASE_URL = "https://whemmzbdmeaeajawzygu.supabase.co"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZW1temJkbWVhZWFqYXd6eWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTgwMzM5MzQsImV4cCI6MjAxMzYwOTkzNH0.9BHaIJyz0cuaW8i3WlRJmWLo-TcDVfFhIXPVj7sOFGM"
SUPABASE_DB_CONNECTION = "postgresql://postgres:uBkEB7w6gaOqCLjn@db.whemmzbdmeaeajawzygu.supabase.co:5432/postgres"
SUPABASE_USERNAME = "Features Copilot"
SUPABASE_PASSWORD = "Favwyg-0mekza"
