[snowflake]
SNOWFLAKE_ACCOUNT = "xxx-xxx"
SNOWFLAKE_USER = ""
SNOWFLAKE_PASSWORD = ""
SNOWFLAKE_DATABASE = "BANKING_ANALYTICS_BUNDLE"
SNOWFLAKE_SCHEMA = "BANKING_INSIGHTS"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"

OPENAI_API_KEY = "sk-XXXXX"

[streamlit]
SUPABASE_URL = "<https://yourapp.supabase.co>"
SUPABASE_KEY = "yourkey"

