-- FOR NCUA_CREDIT_UNION_BRANCHES
-- SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
-- WHERE TABLE_NAME = 'NCUA_CREDIT_UNION_BRANCHES';

SELECT * FROM BANKING_ANALYTICS_BUNDLE.BANKING_INSIGHTS.NCUA_CREDIT_UNION_BRANCHES;