-- FOR FRED_FINANCIAL_LABOR_PERFORMANCE
-- SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
-- WHERE TABLE_NAME = 'FRED_FINANCIAL_LABOR_PERFORMANCE';

SELECT * FROM BANKING_ANALYTICS_BUNDLE.BANKING_INSIGHTS.FRED_FINANCIAL_LABOR_PERFORMANCE;