SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, COMMENT
FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS
ORDER BY TABLE_NAME;

--Gives count of columns
SELECT COUNT(*) FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('FDIC', 'FRED_FINANCIAL_LABOR_PERFORMANCE','FRED_INTEREST_RATE_DATA','FRED_UNEMPLOYEMENT_RATE','NCUA_CREDIT_UNION_BRANCHES');

SELECT COUNT(*) FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('BANK_CHURN_CUSTOMERS','BANK_MARKETING_DATA');

SELECT COUNT(*) FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('COMPANY_CHARACTERISTICS','COMPANY_INDEX','COMPANY_SECURITY_RELATIONSHIPS','GEOGRAPHY_INDEX','OPENFIGI_SECURITY_INDEX','PERMID_SECURITY_INDEX','SEC_CIK_INDEX','SEC_FISCAL_CALENDARS','SEC_HOLDING_FILING_ATTRIBUTES','SEC_HOLDING_FILING_INDEX','SEC_REPORT_ATTRIBUTES','SEC_REPORT_TEXT_ATTRIBUTES');

SELECT * FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_CHURN_CUSTOMERS;

SELECT (COUNT(*) * 100 / (SELECT COUNT(*) FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_CHURN_CUSTOMERS)) AS percentage_jobless
FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_CHURN_CUSTOMERS
WHERE EMPLOYMENT_STATUS = 'Jobless';

SELECT 
    COUNT(*) AS total_customers,
    COUNT(CASE WHEN JOB LIKE '%Manager%' OR JOB LIKE '%Director%' OR JOB LIKE '%Executive%' OR JOB LIKE '%Supervisor%' ) AS management_customers,
    ((COUNT(CASE WHEN JOB LIKE '%Manager%' OR JOB LIKE '%Director%' OR JOB LIKE '%Executive%' OR JOB LIKE '%Supervisor%')) / COUNT(*)) * 100 AS percentage_management_customers
FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_MARKETING_DATA;

SELECT 
    NAME,
    MAX(ASSET) AS largest_assets
FROM 
    BANKING_ANALYTICS_BUNDLE.BANKING_INSIGHTS.FDIC
GROUP BY 
    NAME
ORDER BY 
    largest_assets DESC
LIMIT 1;

SELECT MAX(CREDIT_SCORE) AS highest_credit_score, MIN(CREDIT_SCORE) AS lowest_credit_score
FROM BANKING_INSIGHTS.CHURN_BANK_CUSTOMERS;

--- VIEW TABLE VIEWS


SELECT * FROM BANKING_ANALYTICS_BUNDLE.BANKING_INSIGHTS.FDIC;

-- FOR FDIC 
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FDIC';

-- Create a dedicated database and schema for the FDIC SCHEMA views
CREATE DATABASE IF NOT EXISTS COMPUTE_WH;
CREATE SCHEMA IF NOT EXISTS COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS;

CREATE OR REPLACE VIEW COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FDIC_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FDIC';

SELECT * FROM COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FDIC_INFO_SCHEMA_VIEWS;

-- FRED_FINANCIAL_LABOR_PERFORMANCE INFO SCHEMA VIEWS
CREATE OR REPLACE VIEW COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_FINANCIAL_LABOR_PERFORMANCE_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_FINANCIAL_LABOR_PERFORMANCE';

SELECT * FROM COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_FINANCIAL_LABOR_PERFORMANCE_INFO_SCHEMA_VIEWS;

-- FRED_INTEREST_RATE_DATA INFO SCHEMA VIEWS
CREATE OR REPLACE VIEW COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_INTEREST_RATE_DATA_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_INTEREST_RATE_DATA';

SELECT * FROM COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_INTEREST_RATE_DATA_INFO_SCHEMA_VIEWS;


-- FRED_UNEMPLOYEMENT_RATE INFO SCHEMA VIEWS
CREATE OR REPLACE VIEW COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_UNEMPLOYEMENT_RATE_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_UNEMPLOYEMENT_RATE';

SELECT * FROM COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.FRED_UNEMPLOYEMENT_RATE_INFO_SCHEMA_VIEWS;


-- NCUA_CREDIT_UNION_BRANCHES INFO SCHEMA VIEWS
CREATE OR REPLACE VIEW COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.NCUA_CREDIT_UNION_BRANCHES_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'NCUA_CREDIT_UNION_BRANCHES';

SELECT * FROM COMPUTE_WH.BAKING_ANALYTICS_BUNDLE_VIEWS.NCUA_CREDIT_UNION_BRANCHES_INFO_SCHEMA_VIEWS;


-------------------------


-- FOR FRED_FINANCIAL_LABOR_PERFORMANCE
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_FINANCIAL_LABOR_PERFORMANCE';

-- FOR FRED_INTEREST_RATE_DATA
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_INTEREST_RATE_DATA';

-- FOR FRED_UNEMPLOYEMENT_RATE
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'FRED_UNEMPLOYEMENT_RATE';

-- FOR NCUA_CREDIT_UNION_BRANCHES
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'NCUA_CREDIT_UNION_BRANCHES';

--- This operation is not supported on the shared database 'BANKING_ANALYTICS_BUNDLE'.
SELECT GET_DDL( 'VIEW', 'FDIC' );


------------- BANK MARKETING ---------------------
--Gives count of columns
SELECT COUNT(*) FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('BANK_CHURN_CUSTOMERS', 'BANK_MARKETING_DATA');


SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BANK_CHURN_CUSTOMERS';

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BANK_MARKETING_DATA';


-- Create a dedicated database and schema for the BANK_CHURN_CUSTOMER INFO SCHEMA views
CREATE SCHEMA IF NOT EXISTS COMPUTE_WH.BANK_MARKETING_VIEWS;

-- FOR BANK_CHURN_CUSTOMERS
CREATE OR REPLACE VIEW COMPUTE_WH.BANK_MARKETING_VIEWS.BANK_CHURN_CUSTOMERS_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BANK_CHURN_CUSTOMERS';

SELECT * FROM COMPUTE_WH.BANK_MARKETING_VIEWS.BANK_CHURN_CUSTOMERS_INFO_SCHEMA_VIEWS;

-- FOR BANK_MARKETING_DATA
CREATE OR REPLACE VIEW COMPUTE_WH.BANK_MARKETING_VIEWS.BANK_MARKETING_DATA_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM BANK_MARKETING.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BANK_MARKETING_DATA';

SELECT * FROM COMPUTE_WH.BANK_MARKETING_VIEWS.BANK_MARKETING_DATA_INFO_SCHEMA_VIEWS;

SELECT * FROM  CYBERSYN_SEC_FILINGS.CYBERSYN.SEC_HOLDING_FILING_ATTRIBUTES

SELECT * FROM CYBERSYN_SEC_FILINGS.CYBERSYN.SEC_REPORT_TEXT_ATTRIBUTES

SELECT * FROM BANKING_ANALYTICS_BUNDLE.INFORMATION_SCHEMA.columns WHERE TABLE_NAME = 'FDIC';




------- CYBERSYN_SEC_FILINGS ------------
--Gives count of columns
SELECT COUNT(*) FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('COMPANY_CHARACTERISTICS', 'COMPANY_INDEX','
COMPANY_SECURITY_RELATIONSHIPS','GEOGRAPHY_INDEX','OPENFIGI_SECURITY_INDEX','PERMID_SECURITY_INDEX','SEC_CIK_INDEX','SEC_FISCAL_CALENDARS','
SEC_HOLDING_FILING_ATTRIBUTES','SEC_HOLDING_FILING_INDEX','SEC_REPORT_ATTRIBUTES','SEC_REPORT_INDEX','SEC_REPORT_TEXT_ATTRIBUTES');


-- Create a dedicated database and schema for the BANK_CHURN_CUSTOMER INFO SCHEMA views
CREATE SCHEMA IF NOT EXISTS COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS;

-- FOR COMPANY_CHARACTERISTICS
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_CHARACTERISTICS_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_CHARACTERISTICS';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_CHARACTERISTICS_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_CHARACTERISTICS';


-- FOR COMPANY_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_INDEX';


-- FOR COMPANY_SECURITY_RELATIONSHIPS
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_SECURITY_RELATIONSHIPS_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_SECURITY_RELATIONSHIPS';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.COMPANY_SECURITY_RELATIONSHIPS_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'COMPANY_SECURITY_RELATIONSHIPS';


-- FOR GEOGRAPHY_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.GEOGRAPHY_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'GEOGRAPHY_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.GEOGRAPHY_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'GEOGRAPHY_INDEX';



-- FOR OPENFIGI_SECURITY_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.OPENFIGI_SECURITY_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'OPENFIGI_SECURITY_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.OPENFIGI_SECURITY_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'OPENFIGI_SECURITY_INDEX';



-- FOR PERMID_SECURITY_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.PERMID_SECURITY_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PERMID_SECURITY_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.PERMID_SECURITY_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PERMID_SECURITY_INDEX';



-- FOR SEC_CIK_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_CIK_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_CIK_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_CIK_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_CIK_INDEX';




-- FOR SEC_FISCAL_CALENDARS
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_FISCAL_CALENDARS_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_FISCAL_CALENDARS';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_FISCAL_CALENDARS_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_FISCAL_CALENDARS';



-- FOR SEC_HOLDING_FILING_ATTRIBUTES
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_HOLDING_FILING_ATTRIBUTES_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_HOLDING_FILING_ATTRIBUTES';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_HOLDING_FILING_ATTRIBUTES_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_HOLDING_FILING_ATTRIBUTES';



-- FOR SEC_HOLDING_FILING_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_HOLDING_FILING_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_HOLDING_FILING_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_HOLDING_FILING_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_HOLDING_FILING_INDEX';


-- FOR SEC_REPORT_ATTRIBUTES
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_ATTRIBUTES_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_ATTRIBUTES';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_ATTRIBUTES_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_ATTRIBUTES';



-- FOR SEC_REPORT_INDEX
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_INDEX_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_INDEX';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_INDEX_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_INDEX';


SELECT (COUNT(*) * 100 / (SELECT COUNT(*) FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_MARKETING_DATA)) AS percentage
FROM BANK_MARKETING.BANKING_INSIGHTS.BANK_MARKETING_DATA
WHERE JOB = 'management';

SELECT i.cik, i.company_name, r.period_end_date, r.measure_description, MAX(TO_NUMBER(r.value)) AS value
FROM CYBERSYN_SEC_FILINGS.CYBERSYN.SEC_CIK_INDEX AS i
JOIN CYBERSYN_SEC_FILINGS.CYBERSYN.SEC_REPORT_ATTRIBUTES AS r ON (r.cik = i.cik)
WHERE company_name = 'CHIPOTLE MEXICAN GRILL INC'
AND r.measure_description = 'Number of restaurants'
GROUP BY i.cik, i.company_name, i.cik, r.period_end_date, r.measure_description;

-- FOR SEC_REPORT_TEXT_ATTRIBUTES
CREATE OR REPLACE VIEW COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_TEXT_ATTRIBUTES_INFO_SCHEMA_VIEWS AS
SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_TEXT_ATTRIBUTES';

SELECT * FROM COMPUTE_WH.CYBERSYN_SEC_FILINGS_VIEWS.SEC_REPORT_TEXT_ATTRIBUTES_INFO_SCHEMA_VIEWS;

SELECT TABLE_NAME, DATA_TYPE, COLUMN_NAME, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, COMMENT FROM CYBERSYN_SEC_FILINGS.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SEC_REPORT_TEXT_ATTRIBUTES';


SELECT * FROM CYBERSYN_SEC_FILINGS.CYBERSYN.SEC_HOLDING_FILING_INDEX;

